### ISSUE TITLE
Support output in gibibytes (aka binary prefixes) 

### ISSUE THREAD

**Issue by Mart-Bogdan** [MrDesjardins/pretty-bytes-rust#1]
It's weird to use decimal prefixes, and pretty useless.

Why library don't support binary prefixes?

Like MiB GiB etc. Or in UNIX style like  M K G etc.

**Comment by MrDesjardins** [comment]
@Mart-Bogdan For some reason, I never saw this message. It took over a year to see it! Oops. I see what you mean. I will add it to my bucket list of todos.

**Comment by MrDesjardins** [comment]
@Mart-Bogdan I double-checked and the library supports both. However, it had no unit test, and the documentation in the readme was not clear. Plus, there was a bug that it was showing the unit to be always non binary (the computed number was fine).

I added unit tests and a mention in the readme. I know it's late but hopefully, someone else will find it useful.
The option is `use_1024_instead_of_1000: Some(false)` which can be turned true or false which will handle the division of bytes using 1024 or 1000 and also uses MB or MiB.

E,g,

``` 
-b 2000 -u true
1.95 kbit
```

``` 
-b 2000 -u false
2.00 kB
```

Thanks for your message and hopefully the changes are fixing the initial issue and confusion.
