### ISSUE TITLE
Transitive dependency 'atty' has security issues

### ISSUE THREAD

**Issue by lashomb** [MrDesjardins/pretty-bytes-rust#2]
The crate atty looks like it's been abandoned, so no one is accepting PRs to fix this issue, outlined here: 
https://rustsec.org/advisories/RUSTSEC-2021-0145.html

Is it possible to use a different crate, maybe [std::io::IsTerminal](https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html)?

**Comment by MrDesjardins** [comment]
Thank you @lashomb, for pointing out the situation with Atty. I'm not sure when I'll have the time to make the change, but I will add it to my todo list! Thanks again for your message.

**Comment by MrDesjardins** [comment]
@lashomb Thank you for your message. I have updated the code and published a new version to crates-io.

https://github.com/MrDesjardins/pretty-bytes-rust/commit/6e485c7b1d91e0094f804f5e265246e8f5210de3
